import { BootcampBoxProps } from "@/features/home/components/sub/boot-box";

export const bootcamps: BootcampBoxProps[] = [
  {
    title: "Full-Stack Web Development",
    provider: "AltSchool Africa",
    coverImage: "/images/altschool-cover.png",
    format: "online",
    pace: "full-time",
    status: "enrolling",
    duration: "12 months",
    price: "$600",
    startDate: "Apr 7",
    topics: ["HTML/CSS", "React", "Node.js"],
    href: "/bootcamps/altschool-fullstack",
  },
  {
    title: "Data Science & ML Bootcamp",
    provider: "HNG Internship",
    coverImage: "/images/hng-cover.png",
    format: "online",
    pace: "part-time",
    status: "starting-soon",
    duration: "3 months",
    price: "Free",
    startDate: "Apr 1",
    topics: ["Python", "Pandas", "Sklearn"],
    href: "/bootcamps/hng-datascience",
  },
  {
    title: "UI/UX Design Intensive",
    provider: "Figma Academy",
    coverImage: "/images/figma-academy-cover.png",
    format: "hybrid",
    pace: "part-time",
    status: "enrolling",
    duration: "8 weeks",
    price: "$250",
    startDate: "May 5",
    topics: ["Figma", "Prototyping"],
    href: "/bootcamps/figma-academy",
  },
  {
    title: "Cloud Engineering Track",
    provider: "AWS re/Start",
    coverImage: "/images/aws-restart-cover.png",
    format: "in-person",
    pace: "full-time",
    status: "ended",
    duration: "12 weeks",
    price: "Free",
    topics: ["AWS", "Linux", "Networking"],
    href: "/bootcamps/aws-restart",
  },
];