import { FellowshipBoxProps } from "@/features/home/props/FellowshipBoxProps";

export const fellowships: FellowshipBoxProps[] = [
  {
    title: "Helix Fellowship",
    organization: "African Leadership University",
    coverImage: "/images/helix-cover.png",
    location: "Kigali, Rwanda",
    format: "in-person",
    status: "open",
    duration: "12 months",
    stipend: "$1,200/mo",
    cohort: "2025 Cohort",
    deadline: "Apr 10",
    tags: ["Leadership", "Tech"],
    href: "/fellowships/helix",
  },
  {
    title: "AI Policy Fellows Program",
    organization: "Mozilla Foundation",
    coverImage: "/images/mozilla-cover.png",
    format: "virtual",
    status: "closing-soon",
    duration: "6 months",
    stipend: "$2,000/mo",
    cohort: "Cohort 7",
    deadline: "Mar 30",
    tags: ["Policy", "AI Ethics"],
    href: "/fellowships/mozilla-ai",
  },
  {
    title: "Schwarzman Scholars",
    organization: "Schwarzman College",
    coverImage: "/images/schwarzman-cover.png",
    location: "Beijing, China",
    format: "in-person",
    status: "open",
    duration: "1 year",
    stipend: "Fully funded",
    deadline: "Sep 15",
    tags: ["Global Leadership"],
    href: "/fellowships/schwarzman",
  },
  {
    title: "Code for Africa Fellowship",
    organization: "Code for Africa",
    coverImage: "/images/cfa-cover.png",
    location: "Multiple cities",
    format: "hybrid",
    status: "closed",
    duration: "8 months",
    tags: ["Civic Tech", "Data"],
    href: "/fellowships/code-for-africa",
  },
];