import { GrantBoxProps } from "@/features/home/props/GrantBoxProps";

export const grants: GrantBoxProps[] = [
  {
    title: "African Founders Fund",
    funder: "Techstars Africa",
    coverImage: "/images/techstars-cover.png",
    amount: "$10K–$120K",
    status: "open",
    category: "startup",
    deadline: "May 15",
    eligibility: "African founders",
    tags: ["Equity-free"],
    href: "/grants/techstars-africa",
  },
  {
    title: "Climate Innovation Grant",
    funder: "GreenVC",
    coverImage: "/images/greenvc-cover.png",
    amount: "Up to $50K",
    status: "closing-soon",
    category: "climate",
    deadline: "Mar 28",
    eligibility: "Early-stage startups",
    href: "/grants/greenvc-climate",
  },
  {
    title: "STEM Education Micro-Grant",
    funder: "Mastercard Foundation",
    coverImage: "/images/mastercard-cover.png",
    amount: "$2K–$15K",
    status: "open",
    category: "education",
    deadline: "Jun 1",
    eligibility: "NGOs & educators",
    tags: ["Non-profit"],
    href: "/grants/mastercard-stem",
  },
  {
    title: "Open Source Research Award",
    funder: "Mozilla Foundation",
    coverImage: "/images/mozilla-cover.png",
    amount: "$5K–$30K",
    status: "closed",
    category: "research",
    tags: ["Open Source"],
    href: "/grants/mozilla-research",
  },
];