import { InternBoxProps } from "@/features/home/props/InternBoxProps";

export const internships: InternBoxProps[] = [
  {
    role: "Frontend Engineer Intern",
    company: "Paystack",
    coverImage: "/images/paystack-cover.png",
    location: "Lagos, Nigeria",
    type: "hybrid",
    status: "open",
    stipend: "$800/mo",
    deadline: "Apr 15",
    tags: ["React", "TypeScript"],
    href: "/internships/paystack-frontend",
  },
  {
    role: "ML Research Intern",
    company: "Lelapa AI",
    coverImage: "/images/lelapa-cover.png",
    location: "Remote",
    type: "remote",
    status: "closing-soon",
    stipend: "$600/mo",
    deadline: "Mar 22",
    tags: ["Python", "NLP", "PyTorch"],
    href: "/internships/lelapa-ml",
  },
  {
    role: "Product Design Intern",
    company: "Flutterwave",
    coverImage: "/images/flutterwave-cover.png",
    location: "Lagos, Nigeria",
    type: "onsite",
    status: "open",
    stipend: "$700/mo",
    deadline: "May 1",
    tags: ["Figma", "UX Research"],
    href: "/internships/flutterwave-design",
  },
  {
    role: "Backend Engineer Intern",
    company: "Andela",
    coverImage: "/images/andela-cover.png",
    location: "Remote",
    type: "remote",
    status: "closed",
    tags: ["Node.js", "PostgreSQL"],
    href: "/internships/andela-backend",
  },
];