import { JobBoxProps } from "@/features/home/props/JobBoxProps";

export const jobs: JobBoxProps[] = [
  {
    title: "Senior Full-Stack Engineer",
    company: "Moniepoint",
    coverImage: "/images/moniepoint-cover.png",
    location: "Lagos, Nigeria",
    type: "hybrid",
    status: "open",
    level: "senior",
    salary: "$60K–$80K",
    deadline: "Apr 30",
    tags: ["React", "Go", "Postgres"],
    href: "/jobs/moniepoint-fullstack",
  },
  {
    title: "Data Scientist",
    company: "54gene",
    coverImage: "/images/54gene-cover.png",
    location: "Abuja, Nigeria",
    type: "onsite",
    status: "open",
    level: "mid",
    salary: "$40K–$55K",
    tags: ["Python", "R", "ML"],
    href: "/jobs/54gene-datascience",
  },
  {
    title: "DevOps Engineer",
    company: "Kuda Bank",
    coverImage: "/images/kuda-cover.png",
    location: "Remote",
    type: "remote",
    status: "closing-soon",
    level: "senior",
    salary: "$70K+",
    deadline: "Mar 25",
    tags: ["Kubernetes", "AWS", "Terraform"],
    href: "/jobs/kuda-devops",
  },
  {
    title: "Product Manager",
    company: "Interswitch",
    coverImage: "/images/interswitch-cover.png",
    location: "Lagos, Nigeria",
    type: "hybrid",
    status: "closed",
    level: "lead",
    tags: ["Fintech", "Agile"],
    href: "/jobs/interswitch-pm",
  },
];
