
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import CustomScrollbar from "@/components/ui/ScrollNav";
// import { Toaster } from "react-hot-toast";

// ─── Theme Provider ───────────────────────────────────────
import { ThemeProvider } from "next-themes";
import ClientNavbar from "@/components/layout/ClientNavbar";
import { Toaster } from "sonner";
import Footer from "@/features/landing/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Important: suppressHydrationWarning prevents mismatch warnings
      suppressHydrationWarning
      className={cn("font-sans", inter.variable)}
    >
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased min-h-screen",
        )}
      >
        
         
          <Toaster position="top-right"  />
          

          <CustomScrollbar />
          
                <ClientNavbar />

          
          {children}
                <Footer />
        
      </body>
    </html>
  );
}