
import { HackerProfile } from "@/features/hacker/types/hacker.types";
export type Status = "active" | "in_hackathon" | "offline" | "logged_out" | "busy" | "grinding";



const hackers: HackerProfile[] = [
  {
    id: "4",
    username: "ByteCrafter",
    handle: "@bytecrafter",
    avatarUrl: "https://i.pinimg.com/736x/cb/33/d8/cb33d80fe655e221ae05f41c8edd0cdb.jpg",
    location: "Cambridge, MA",
    roles: ["Full-Stack Developer", "AI Engineer"],
    organization: "MIT",
    techStack: ["React", "Node.js", "Python", "TensorFlow"],
    bio: "Building scalable systems and AI-powered apps.",
    skills: ["Full-Stack"],
    interest: "Hackathons, Startups, Open Source",
    following: 10,
    followers: 52,
    status:'in_hackathon',
    karma: 90,
    activity: [
      { month: "Apr", value: 2 }, { month: "May", value: 4 },
      { month: "Jun", value: 6 }, { month: "Jul", value: 8 },
      { month: "Aug", value: 10 }, { month: "Sep", value: 12 },
      { month: "Oct", value: 14 }, { month: "Nov", value: 16 },
      { month: "Dec", value: 18 }, { month: "2026", value: 20 },
      { month: "Feb", value: 22 }, { month: "Mar", value: 24 },
    ],
    socialLinks: { github: "https://github.com/bytecrafter" },
  },
  {
    id: "5",
    username: "DevNova",
    handle: "@devnova",
    avatarUrl: "https://i.pinimg.com/736x/86/1b/44/861b44c51302264840292cdbb211ca9a.jpg",
    location: "Lagos, Nigeria",
    roles: ["Frontend Developer", "Design Systems Engineer"],
    organization: "University of Lagos",
    techStack: ["React", "TypeScript", "Figma", "Tailwind CSS"],
    bio: "Passionate about frontend and design systems.",
    skills: ["Frontend", "UX/UI"],
    interest: "Hackathons, Startups, Open Source",
    following: 5,
    followers: 30,
        status:'active',

    karma: 60,
    activity: [
      { month: "Apr", value: 1 }, { month: "May", value: 2 },
      { month: "Jun", value: 3 }, { month: "Jul", value: 5 },
      { month: "Aug", value: 6 }, { month: "Sep", value: 7 },
      { month: "Oct", value: 9 }, { month: "Nov", value: 10 },
      { month: "Dec", value: 12 }, { month: "2026", value: 14 },
      { month: "Feb", value: 16 }, { month: "Mar", value: 18 },
    ],
    socialLinks: { github: "https://github.com/devnova" },
  },
  {
    id: "6",
    username: "ChainWizard",
    handle: "@chainwizard",
    avatarUrl: "https://i.pinimg.com/736x/0f/64/d5/0f64d5d7d6de8cace11d5cf11bc2de8a.jpg",
    location: "Berlin, Germany",
    roles: ["Smart Contract Engineer", "Web3 Developer"],
    organization: "Ethereum Dev Guild",
    techStack: ["Solidity", "Hardhat", "TypeScript", "React", "ethers.js"],
    bio: "Smart contract engineer and Web3 enthusiast.",
    skills: ["Blockchain", "Full-Stack"],
    interest: "Web3 development, DeFi innovation, decentralized systems",
    following: 20,
    followers: 95,
        status:'offline',

    karma: 130,
    activity: [
      { month: "Apr", value: 4 }, { month: "May", value: 6 },
      { month: "Jun", value: 8 }, { month: "Jul", value: 10 },
      { month: "Aug", value: 12 }, { month: "Sep", value: 15 },
      { month: "Oct", value: 18 }, { month: "Nov", value: 20 },
      { month: "Dec", value: 22 }, { month: "2026", value: 25 },
      { month: "Feb", value: 28 }, { month: "Mar", value: 32 },
    ],
    socialLinks: { github: "https://github.com/chainwizard" },
  },
  {
    id: "7",
    username: "PixelSmith",
    handle: "@pixelsmith",
    avatarUrl: "https://i.pinimg.com/avif/1200x/47/d8/99/47d899ef8ef2ed4b45bf86f4082ead17.avf",
    location: "Toronto, Canada",
    roles: ["UI/UX Designer", "Frontend Developer"],
    organization: "Freelance",
    techStack: ["Figma", "React", "Framer Motion", "Tailwind CSS"],
    bio: "UI/UX designer crafting pixel-perfect interfaces.",
    skills: ["UX/UI", "Frontend"],
    interest: "Design systems, motion design, accessibility",
    following: 8,
    followers: 44,
        status:'active',

    karma: 70,
    activity: [
      { month: "Apr", value: 1 }, { month: "May", value: 3 },
      { month: "Jun", value: 4 }, { month: "Jul", value: 5 },
      { month: "Aug", value: 7 }, { month: "Sep", value: 8 },
      { month: "Oct", value: 10 }, { month: "Nov", value: 11 },
      { month: "Dec", value: 13 }, { month: "2026", value: 14 },
      { month: "Feb", value: 16 }, { month: "Mar", value: 18 },
    ],
    socialLinks: { github: "https://github.com/pixelsmith" , website: 'ex.com'},
  },
  {
    id: "8",
    username: "DataPhantom",
    handle: "@dataphantom",
    avatarUrl: "https://i.pinimg.com/avif/1200x/3e/f3/50/3ef350dc86cc82a092463e5d795654b5.avf",
    location: "Stanford, CA",
    roles: ["Data Scientist", "ML Engineer"],
    organization: "Stanford University",
    techStack: ["Python", "PyTorch", "scikit-learn", "SQL", "Jupyter"],
    bio: "Data science + ML = magic.",
    skills: ["Backend"],
    interest: "Machine learning, data pipelines, open datasets",
    following: 15,
    followers: 80,
        status:'grinding',

    karma: 115,
    activity: [
      { month: "Apr", value: 3 }, { month: "May", value: 5 },
      { month: "Jun", value: 8 }, { month: "Jul", value: 10 },
      { month: "Aug", value: 13 }, { month: "Sep", value: 15 },
      { month: "Oct", value: 17 }, { month: "Nov", value: 20 },
      { month: "Dec", value: 22 }, { month: "2026", value: 24 },
      { month: "Feb", value: 27 }, { month: "Mar", value: 30 },
    ],
    socialLinks: { github: "https://github.com/dataphantom" , website: 'example.com'},
  },
  {
    id: "9",
    username: "CodeRift",
    handle: "@coderift",
    avatarUrl: "https://i.pinimg.com/1200x/54/da/0d/54da0d6e699ba9d3b5a27647deb7f60a.jpg",
    location: "Nairobi, Kenya",
    roles: ["Full-Stack Developer", "Blockchain Developer"],
    organization: "Google Developer Student Club",
    techStack: ["C", "Python", "Solidity", "EVM"],
    bio: "Fullstack dev who loves hackathons.",
    skills: ["Full-Stack", "Blockchain"],
    interest: "Web3 development, reactive smart contracts, real-time blockchain applications",
    following: 22,
    followers: 60,
        status:'offline',

    karma: 88,
    activity: [
      { month: "Apr", value: 2 }, { month: "May", value: 4 },
      { month: "Jun", value: 5 }, { month: "Jul", value: 7 },
      { month: "Aug", value: 9 }, { month: "Sep", value: 11 },
      { month: "Oct", value: 13 }, { month: "Nov", value: 15 },
      { month: "Dec", value: 17 }, { month: "2026", value: 19 },
      { month: "Feb", value: 21 }, { month: "Mar", value: 23 },
    ],
    socialLinks: { github: "https://github.com/coderift" , website: 'example.com'},
  },
  {
    id: "10",
    username: "ZypherX",
    handle: "@zypherx",
    avatarUrl: "https://i.pinimg.com/1200x/4a/f5/69/4af5692b4de4bbd092e9c7cc07316fd9.jpg",
    location: "Remote",
    roles: ["AI Engineer", "Automation Developer"],
    organization: "Freelance",
    techStack: ["C", "Node.js", "Rust", "EVM"],
    bio: "Exploring the edges of AI and automation.",
    skills: ["Backend", "Blockchain"],
    interest: "Web3 development, DeFi innovation, building scalable on-chain solutions",
    following: 18,
    followers: 74,
        status:'active',

    karma: 100,
    activity: [
      { month: "Apr", value: 3 }, { month: "May", value: 5 },
      { month: "Jun", value: 7 }, { month: "Jul", value: 9 },
      { month: "Aug", value: 11 }, { month: "Sep", value: 13 },
      { month: "Oct", value: 15 }, { month: "Nov", value: 17 },
      { month: "Dec", value: 20 }, { month: "2026", value: 22 },
      { month: "Feb", value: 25 }, { month: "Mar", value: 28 },
    ],
    socialLinks: { github: "https://github.com/zypherx", website: 'example.com' },
  },
  {
    id: "11",
    username: "NovaStack",
    handle: "@novastack",
    avatarUrl: "https://i.pinimg.com/avif/736x/29/7c/13/297c13cf88d50a699807ca1d8a11a6c1.avf",
    location: "Cambridge, MA",
    roles: ["Product Engineer", "Full-Stack Developer"],
    organization: "Harvard University",
    techStack: ["Python", "Solidity", "React", "AWS"],
    bio: "Building products that scale globally.",
    skills: ["Full-Stack", "Blockchain"],
    interest: "Web3 development, reactive smart contracts, decentralized systems",
    following: 25,
    followers: 110,
        status:'active',

    karma: 150,
    activity: [
      { month: "Apr", value: 5 }, { month: "May", value: 8 },
      { month: "Jun", value: 10 }, { month: "Jul", value: 12 },
      { month: "Aug", value: 15 }, { month: "Sep", value: 18 },
      { month: "Oct", value: 20 }, { month: "Nov", value: 22 },
      { month: "Dec", value: 25 }, { month: "2026", value: 28 },
      { month: "Feb", value: 31 }, { month: "Mar", value: 34 },
    ],
    socialLinks: { github: "https://github.com/novastack", website: 'example.com' },
  },
  {
    id: "12",
    username: "AlgoKnight",
    handle: "@algoknight",
    avatarUrl: "https://i.pinimg.com/1200x/d2/b7/66/d2b766828fdb4c0e5cc104a1f2bdc4c2.jpg",
    location: "Pittsburgh, PA",
    roles: ["Competitive Programmer", "Backend Developer"],
    organization: "Carnegie Mellon University",
    techStack: ["C++", "Python", "React", "Node.js"],
    bio: "Algorithms, problem-solving, and competitive coding.",
    skills: ["Backend", "Full-Stack"],
    interest: "Hackathons, Startups, Open Source, competitive programming",
    following: 12,
    followers: 65,
        status:'busy',

    karma: 95,
    activity: [
      { month: "Apr", value: 2 }, { month: "May", value: 5 },
      { month: "Jun", value: 7 }, { month: "Jul", value: 9 },
      { month: "Aug", value: 11 }, { month: "Sep", value: 13 },
      { month: "Oct", value: 16 }, { month: "Nov", value: 18 },
      { month: "Dec", value: 20 }, { month: "2026", value: 22 },
      { month: "Feb", value: 24 }, { month: "Mar", value: 26 },
    ],
    socialLinks: { github: "https://github.com/algoknight" , website: 'example.com'},
  },
  {
    id: "13",
    username: "SkyBuilder",
    handle: "@skybuilder",
    avatarUrl: "https://i.pinimg.com/avif/1200x/93/b4/0c/93b40ceea38b238699f2fc5c1c3a433a.avf",
    location: "Remote",
    roles: ["Full-Stack Developer", "Blockchain Engineer"],
    organization: "Independent",
    techStack: ["Python", "Solidity", "React", "EVM"],
    bio: "Turning ideas into deployed products fast.",
    skills: ["Full-Stack", "Blockchain"],
    interest: "Web3 development, DeFi innovation, building scalable on-chain solutions",
    following: 30,
    followers: 130,
        status:'busy',

    karma: 160,
    activity: [
      { month: "Apr", value: 6 }, { month: "May", value: 9 },
      { month: "Jun", value: 12 }, { month: "Jul", value: 14 },
      { month: "Aug", value: 17 }, { month: "Sep", value: 19 },
      { month: "Oct", value: 22 }, { month: "Nov", value: 24 },
      { month: "Dec", value: 27 }, { month: "2026", value: 30 },
      { month: "Feb", value: 33 }, { month: "Mar", value: 36 },
    ],
    socialLinks: { github: "https://github.com/skybuilder" , website: 'example.com'},
  },
];

// Build a Record keyed by id — typed explicitly so string-indexed lookups are safe
export const MOCK_HACKERS: Record<string, HackerProfile> = Object.fromEntries(
  hackers.map((h) => [h.id, h])
);

// Keep a plain array export for components that need to iterate
export const MOCK_HACKERS_LIST: HackerProfile[] = hackers;